
def train_model():
    # Add code to train the model here
    # Put all input files needed to train the model, and all output files generated by the training
    # in the data/ folder, and publish it with dvc and DagsHub
    return {
        'precision': 0.85,
        'recall': 0.80,
        'accuracy': 0.85,
        'roc_auc': 0.90,
        'f1': 0.75,
        'average_precision': 0.85,
    }


if __name__ == '__main__':
    print(train_model())